# Generated by Django 3.2.9 on 2021-12-07 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20211207_1610'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bids',
            new_name='Bid',
        ),
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='Auction_Listings',
            new_name='Listing',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='listings',
            new_name='listing',
        ),
    ]
